server:
  port: ${SERVER_PORT:${PORT:8080}}
management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  main:
    web-application-type: none

app:
  queue:
    name: orders
  blob:
    container: audit

azure:
  storage:
    connection-string: >
      DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;
      AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;
      BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
      QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;
      TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
